apiVersion: v1
kind: Secret
metadata:
  name: products-app
  namespace: products
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: "cG9zdGdyZXM="
  SPRING_DATASOURCE_PASSWORD: "bWlzZW5oYXN1cGVyc2VjcmV0YQ=="
  SPRING_FLYWAY_USER: "cG9zdGdyZXM="
  SPRING_FLYWAY_PASSWORD: "bWlzZW5oYXN1cGVyc2VjcmV0YQ=="