apiVersion: v1
kind: Service
metadata:
  name: products-db
  namespace: products
spec:
  type: ClusterIP # Exposto apenas dentro do cluster
  selector:
    app: products-db # Aponta para o Deployment 'products-db'
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432